### ISSUE TITLE
Readme has a broken link "set up your test environment"

### ISSUE THREAD

**Issue by guilhermefront** [next-page-tester/next-page-tester#291]
## 🐛 Bug Report
Broken link on the "set up your test environment" link in this section https://github.com/toomuchdesign/next-page-tester#error-not-implemented-windowscrollto

![image](https://user-images.githubusercontent.com/49620737/148704189-5d50dbbc-e270-4c63-99fe-8d49f094caf6.png)

## Reproduction

Click on the link and nothing happens

## Expected behavior

I expected the link to go to an explanation about setting up my test environment

**Comment by toomuchdesign** [comment]
Hey @guilhermefront, feel free to open a PR to fix it. Thanks
