### ISSUE TITLE
error Command failed with signal "SIGSEGV".

### ISSUE THREAD

**Issue by railsfactory-sivamanikandan** [next-page-tester/next-page-tester#292]
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by RichMatthews** [comment]
I'm also getting this issue

**Comment by tylerzey** [comment]
Any idea what might be causing this? I'm also getting this issue.

**Comment by jasonwilliams** [comment]
Could you provide some steps to reproduce?

**Comment by narliecholler** [comment]
any update on this??

**Comment by DoroGi** [comment]
I also had this issue. I tried debugging it a bit.

For me it breaks at the first getPage I try, on this line:
https://github.com/next-page-tester/next-page-tester/blob/4cea3f87801632f9f21644c2cad7efb15605cafe/src/nextConfig.ts#L37
The value of nextRoot is correct.

I have an extremely basic next.config.js
`module.exports = {
  basePath: '/pagine',
  reactStrictMode: true,
  poweredByHeader: false,
  serverRuntimeConfig: {},
  publicRuntimeConfig: {},
};
`

Next version: 12.0.7
next-page-tester: 0.31.0
running on IOS

Hope this helps!

**Comment by toomuchdesign** [comment]
Closing since there's no repro and there's no way to ensure whether still relevant.
