### ISSUE TITLE
next image config moved in v12.1.1+

### ISSUE THREAD

**Issue by florian-milky** [next-page-tester/next-page-tester#298]
## 🐛 Bug Report

image config import moved in next: 
https://github.com/vercel/next.js/pull/34677/files
[packages/next/shared/lib/image-config.ts](https://github.com/vercel/next.js/pull/34677/files#diff-4a94041e82272cf6fd6703f0508494a02f73a25f6a8498271278691b5e478052)

**Comment by jasonwilliams** [comment]
@florian-milky are you able to help us by doing a PR for this change? We're low on contributors right now and would appreciate it.

**Comment by Zach-Jaensch** [comment]
If I get time do you mind if I look at creating a PR? 

In the mean time to help others until the fix can be released, in your jest config add the following:
```json
{
  "moduleNameMapper": {
    "next/dist/server/image-config": "<rootDir>/node_modules/next/dist/shared/lib/image-config"
  }
}
```

**Comment by paul-pro** [comment]
@Zach-Jaensch @jasonwilliams sorry, it was a oneliner to fix so I've opened a PR. Please take a look
